export const FETCH_PROJECTS = "FETCH_PROJECTS";
export const FETCH_PROJECTS_SUCCESS = "FETCH_PROJECTS_SUCCESS";
export const FETCH_PROJECTS_ERROR = "FETCH_PROJECTS_ERROR";

export const DELETE_PROJECT = "DELETE_PROJECT";
export const DELETE_PROJECT_ERROR = "DELETE_PROJECT_ERROR";

export const UPDATE_PROJECT = "UPDATE_PROJECT";
export const UPDATE_PROJECT_ERROR = "UPDATE_PROJECT_ERROR";

export const FETCH_PROJECT = "FETCH_PROJECT";
export const FETCH_PROJECT_ERROR = "FETCH_PROJECT_ERROR";

export const CREATE_PROJECT = "CREATE_PROJECT";
export const CREATE_PROJECT_ERROR = "CREATE_PROJECT_ERROR";
